"""init table

Revision ID: 2bcfa2e5a0a2
Revises: 0afbf46445e8
Create Date: 2026-05-17 21:12:28.795983

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2bcfa2e5a0a2"
down_revision: Union[str, Sequence[str], None] = "0afbf46445e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
