"""add question fields

Revision ID: cd798829f1b9
Revises: 2bcfa2e5a0a2
Create Date: 2026-05-19 19:34:33.713425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd798829f1b9'
down_revision: Union[str, Sequence[str], None] = '2bcfa2e5a0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('concept_ids', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('kc_routes_cleaned', sa.JSON(), nullable=True))
    op.add_column(
        'questions',
        sa.Column('option_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.alter_column('questions', 'option_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'option_count')
    op.drop_column('questions', 'kc_routes_cleaned')
    op.drop_column('questions', 'concept_ids')
    # ### end Alembic commands ###
